config/routes.rb
MobileEventGallery::Application.routes.draw do
  devise_for :admins

  root :to => "images#index"
  resources :images, only: [:index, :show]
  resources :admins, only: [] do
    resources :images, except: [:index, :show]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(admin=nil)
    if admin.is_a?(Admin)
      can :manage, :all
    else
      #TODO add abilities
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :validatable

  attr_accessible :email, :password, :password_confirmation
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :etag, :content_type, :url, :photo, presence: true

  mount_uploader :photo, PhotoUploader
  scope :unprocessed, where(state: :pending)
  scope :approved, where(state: :approved)

  after_save do
    self.delay.update_twitter_if_approved if state == "approved" && !shared_on_twitter?
  end

  MAX_RETRY_COUNT_FOR_STATUS_UPDATE = 10


  def import_remote_photo!
    self.remote_photo_url = image_url_without_params
    self.photo?
  end

  def image_url_without_params
    uri = URI(url)
    uri.query = "" if uri.query.present?
    uri.to_s
  end

  def update_twitter_if_approved
    tries = 0
    begin
      Twitter.update_with_media("", File.new(photo.path))
    rescue Twitter::Error::Forbidden
      if tries < MAX_RETRY_COUNT_FOR_STATUS_UPDATE
        tries += 1
        retry
      end
    end
  end

  def photo_url
    Rails.configuration.domain+photo.url
  end

  def as_json(options={})
    {id: id, uploaded_at: uploaded_at, photo_url: photo_url}
  end

  class << self

    def fetch_and_store_remote!
      parsed_json = PendingImage::Request.new.parsed_json
      images = PendingImage::Builder.new(parsed_json).images
      remote_image_collection = PendingImage::Collection.new(images, except_etags: existing_image_etags)
      remote_image_collection.save!
    end

    def existing_image_etags
      Image.all.map(&:etag)
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    render_unauthorized
  end

  def current_ability
    @current_ability ||= Ability.new(current_admin)
  end

  def render_unauthorized
    render "#{Rails.root}/public/401", status: :unauthorized, layout: false, :format => :html
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  load_and_authorize_resource :admin, except: [:index, :show]
  load_resource

  def index
    @approved_images = Image.approved
    respond_to do |format|
      format.html
      format.json { render json: @approved_images }
    end
  end

  def show
  end

  def new
    respond_to do |format|
      format.js {
        Image.fetch_and_store_remote! and @pending_images = Image.unprocessed
      }
      format.html { @pending_images = Image.unprocessed }
    end
  end

  def update
    @image.update_attributes(params[:image])
  end

  def destroy
    @image.update_attribute(:state, "rejected")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/approved_images_helper.rb
module ApprovedImagesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
  def pending_image_list_title
    content_tag("h1", @pending_images.empty? ? "There are no new images" : "Newest unapproved images")
  end

  def approved_image_list_title
    content_tag("h1", @approved_images.empty? ? "No images here" : "Latest images")
  end
end

app/views/images/_pending_image_list.html.haml
= pending_image_list_title
%ul.thumbnails
  - pending_images.each do |image|
    %li.span3{id: "image_block_#{image.id}"}
      .thumbnail
        = link_to image_tag(image.photo.list.url), image.photo.url
        = simple_form_for([admin, image], remote: true) do |form|
          = form.hidden_field :state, value: "approved"
          = form.submit "Approve", class: "btn btn-success approve-button"
          = link_to "Reject", admin_image_path(admin_id: admin, id: image), remote: true, method: "DELETE", class: "btn btn-danger reject-button"
.well
  =link_to "Load new images", new_admin_image_path(admin_id: @admin), remote: true, class: "btn btn-large btn-block btn-primary", id: "download-images-link", data: {"loading-text" => "Downloading images please wait it might take a while..."}

app/views/images/destroy.js.haml
$("form#edit_image_#{@image.id}").replaceWith("<div class='alert alert-error'>Rejected!<div>")

app/views/images/index.html.haml
= approved_image_list_title
%ul.thumbnails
  - @approved_images.each do |image|
    %li.span3{id: "image_block_#{image.id}"}
      .thumbnail
        = link_to image_tag(image.photo.list.url, height: "100"), image_path(image)

app/views/images/new.html.haml
#pending-image-list
  = render "pending_image_list", pending_images: @pending_images, admin: @admin

app/views/images/new.js.haml
$("#pending-image-list").html("#{escape_javascript(render "pending_image_list", pending_images: @pending_images, admin: @admin)}")

app/views/images/show.html.haml
= image_tag @image.photo.url

app/views/images/update.js.haml
$("form#edit_image_#{@image.id}").replaceWith("<div class='alert alert-success'>Approved!</div>")

app/views/layouts/_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand(href="/") Mobile Event Gallery
      .container.nav-collapse
        %ul.nav.pull-left
          %li= link_to "Home", root_path
          - if admin_signed_in?
            %li= link_to "Pending images", new_admin_image_path(admin_id: current_admin)
        %ul.nav.pull-right
          - if admin_signed_in?
            %li= link_to "Sign out", destroy_admin_session_path, method: "DELETE"
          - else
            %li= link_to "Sign in", new_admin_session_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Mobile Event Gallery"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link{href: "/assets/favicon.ico", rel: "shortcut icon"}


  %body
    = render "layouts/navigation"

    .container-fluid
      .row
        .span12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Janis 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"